// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwcxkxsajshvnuezlucj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3Y3hreHNhanNodm51ZXpsdWNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTYxNTQsImV4cCI6MjA1OTk3MjE1NH0.ITcCA8HgzTP7uVFIUxlJyVHmxBgbq3zXebRxKw_tDsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);